### ISSUE TITLE
error running on macos

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Broadsea-Achilles#4]
I built the dockerfile locally after cloning this repository but received the following error when executing the command from the README.

fjd@franks-mbp Broadsea-Achilles % docker run \
    -e ACHILLES_SOURCE="postgresql://host.docker.internal:5432/postgres" \
    -e ACHILLES_DB_USERNAME="postgres_user" \
    -e ACHILLES_DB_PASSWORD="postgres_password" \
    achilles                                
Loading required package: DatabaseConnector
2022-05-03 00:24:41	Beginning single-threaded execution
Connecting using PostgreSQL driver
Error in rJava::.jcall(jdbcDriver, "Ljava/sql/Connection;", "connect",  : 
  org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Calls: achilles ... connect -> connectUsingJdbcDriver -> <Anonymous> -> .jcheck
Execution halted

**Comment by chgl** [comment]
I think it should be `ACHILLES_DB_URI` instead of `ACHILLES_SOURCE`. the former defaults to `"postgresql://localhost:5432/postgres"` which would explain the error. I've taken the default values from the initial container-based version, but it might be clearer to not set defaults and instead error on unset variables.

I am unfortunately not very familiar with R, so I don't know if there's a helpful package to manage configuration from env vars including validation.
